# Copyright (c) SenseTime. All Rights Reserved.

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

from yacs.config import CfgNode as CN

__C = CN()

cfg = __C

__C.META_ARC = "siamban_r50_l234"

__C.CUDA = True

# ------------------------------------------------------------------------ #
# Training options
# ------------------------------------------------------------------------ #
__C.TRAIN = CN()

# Number of negative
__C.TRAIN.NEG_NUM = 16

# Number of positive
__C.TRAIN.POS_NUM = 16

# Number of anchors per images
__C.TRAIN.TOTAL_NUM = 64

__C.TRAIN.NEGPOS_RATIO = 3.0

__C.TRAIN.EXEMPLAR_SIZE = 127

__C.TRAIN.SEARCH_SIZE = 255
__C.TRAIN.SEARCH_DET_SIZE = 255


__C.TRAIN.BASE_SIZE = 8

__C.TRAIN.OUTPUT_SIZE = 19
__C.TRAIN.OUTPUT_SIZE_DET = 19


__C.TRAIN.RESUME = ''

__C.TRAIN.PRETRAINED = ''

__C.TRAIN.LOG_DIR = './logs'

__C.TRAIN.SNAPSHOT_DIR = './snapshot'

__C.TRAIN.EPOCH = 20

__C.TRAIN.START_EPOCH = 0

__C.TRAIN.BATCH_SIZE = 32

__C.TRAIN.NUM_WORKERS = 1

__C.TRAIN.MOMENTUM = 0.9

__C.TRAIN.WEIGHT_DECAY = 0.0001
__C.TRAIN.WEIGHT_DECAY_BB = 0.0001

__C.TRAIN.CLS_WEIGHT = 1.0

__C.TRAIN.LOC_WEIGHT = 1.0
__C.TRAIN.LOC_WEIGHT_L1 = 1.0

__C.TRAIN.MASK_WEIGHT = 1.0
__C.TRAIN.AFL1_WEIGHT = 0.0

__C.TRAIN.KL_WEIGHT = 1.0

__C.TRAIN.RANK_CLS_WEIGHT = 0.5

__C.TRAIN.RANK_IGR_WEIGHT = 0.25
__C.TRAIN.RANK_IGR_MODE = 0

__C.TRAIN.HARD_NEGATIVE_THS = 0.5

__C.TRAIN.RANK_NUM_HARD_NEGATIVE_SAMPLES = 8

__C.TRAIN.IoU_Gamma = 3

__C.TRAIN.HARD_NEGATIVE_THS = 0.5

__C.TRAIN.PRINT_FREQ = 20

__C.TRAIN.LOG_GRADS = False

__C.TRAIN.GRAD_CLIP = 10.0

__C.TRAIN.BASE_LR = 0.005

__C.TRAIN.LR = CN()

__C.TRAIN.LR.TYPE = 'log'

__C.TRAIN.LR.KWARGS = CN(new_allowed=True)

__C.TRAIN.LR_WARMUP = CN()

__C.TRAIN.LR_WARMUP.WARMUP = True

__C.TRAIN.LR_WARMUP.TYPE = 'step'

__C.TRAIN.LR_WARMUP.EPOCH = 5

__C.TRAIN.LR_WARMUP.KWARGS = CN(new_allowed=True)


__C.TRAIN.DATA_NORMALIZE = True
__C.TRAIN.DATA_NORMALIZE_MODE = 1
__C.TRAIN.FLAG_SIGMOID_LOSS = True
__C.TRAIN.CODE_TIME_TAGE = 'T0'
__C.TRAIN.FLAG_LOCPREDMODE = 0
__C.TRAIN.TYPE_ACM = 0
__C.TRAIN.CONVTYPE_XORR = 0
__C.TRAIN.FLAG_REPARAMETERALL = False
__C.TRAIN.MODE_REPARAMETERIZE = 0

__C.TRAIN.NORM_REG_TARGETS = True
__C.TRAIN.CENTER_SAMPLING_RADIUS = 1.5
__C.TRAIN.FPN_STRIDES = [8,]
__C.TRAIN.IOU_LOSS_TYPE = 'linear_iou'
__C.TRAIN.CLS_LOSS_TYPE = 'default'

__C.TRAIN.FOCAL_ALPHA = 0.25
__C.TRAIN.FOCAL_GAMA = 2.0
__C.TRAIN.OBJECT_SIZES_OF_INTEREST = [16,255]
__C.TRAIN.NUM_CLASSES = 200
__C.TRAIN.FLAG_FOCAL_LOSS = True

__C.TRAIN.YNRBO = True
__C.TRAIN.IoU_Gamma1=5
__C.TRAIN.IoU_Gamma2=1
__C.TRAIN.IGR2 = False
__C.TRAIN.IGR2_EPOCH = 5
__C.TRAIN.NPOS_SEL_RANK = 20
__C.TRAIN.SIGGMA_GAUSSIONBB = 3.0
__C.TRAIN.SIGGMA_GAUSSIONOTHER = 3.0

# __C.TRAIN.FPN_STRIDES = [8,]
# __C.TRAIN.CENTER_SAMPLING_RATIUS = 2.5
# __C.TRAIN.IOU_LOSS_TYPE = 'giou'
# __C.TRAIN.OBJECT_SIZES_OF_INTEREST = [5,]
__C.TRAIN.PROB_DROPOUT=0.0
__C.TRAIN.PROB_DROPOUTSPATIAL=0.0
__C.TRAIN.FLAGCLS_CENTERWEIGHT=False
__C.TRAIN.FLAGLOC_CENTERWEIGHT=False
__C.TRAIN.FLAGCLASSONCORR = False

__C.TRAIN.CHANNELS_ASPP = 192
__C.TRAIN.RATES_ASPP = [2,4,6,8]

__C.TRAIN.CENTER_SIZE = 9
__C.TRAIN.BBADDWEIGHT = [0.3,0.3,0.3]
__C.TRAIN.FLAG_LOC_EXP = True
__C.TRAIN.FLAG_MIXEDPRECISION = False
__C.TRAIN.FLAG_OPTIMIZER_ADAM = False
__C.TRAIN.FLAG_OPTIMIZER_ADAM = False
__C.TRAIN.RPN_HEADCHANNELS = 32

# ------------------------------------------------------------------------ #
# Dataset options
# ------------------------------------------------------------------------ #
__C.DATASET = CN(new_allowed=True)

# Augmentation
# for template
__C.DATASET.TEMPLATE = CN()

# Random shift see [SiamPRN++](https://arxiv.org/pdf/1812.11703)
# for detail discussion
__C.DATASET.TEMPLATE.SHIFT = 4
__C.DATASET.TEMPLATE.SHIFT_RATIO = 0.01

__C.DATASET.TEMPLATE.SCALE = 0.05

__C.DATASET.TEMPLATE.BLUR = 0.0

__C.DATASET.TEMPLATE.FLIP = 0.0
__C.DATASET.TEMPLATE.SHIFT_RATIO = 1.0

__C.DATASET.TEMPLATE.COLOR = 1.0

__C.DATASET.SEARCH = CN()

__C.DATASET.SEARCH.SHIFT = 64

__C.DATASET.SEARCH.SCALE = 0.18
__C.DATASET.SEARCH.SCALE_MIN = 1.0
__C.DATASET.SEARCH.SCALE_MAX = 1.0
__C.DATASET.SEARCH.SCALE_HWRATIO = 0.1
__C.DATASET.SEARCH.SHIFT_RATIO = 0.0

__C.DATASET.SEARCH.BLUR = 0.0

__C.DATASET.SEARCH.FLIP = 0.0

__C.DATASET.SEARCH.COLOR = 1.0

__C.DATASET.SEARCH.PROB_RANDEREASE = 0.0
__C.DATASET.SEARCH.SCALEMIN_RANDEREASE = 0.0
__C.DATASET.SEARCH.SCALEMAX_RANDEREASE = 0.0

__C.DATASET.SEARCH.MINSIZE_TARGET = 16
__C.DATASET.SEARCH.NUM_REPEATE = 6


# Sample Negative pair see [DaSiamRPN](https://arxiv.org/pdf/1808.06048)
# for detail discussion
__C.DATASET.NEG = 0.2
__C.DATASET.NUM_NEG = 1
__C.DATASET.NUM_POS = 1
__C.DATASET.POSNEG_MODE = 0
__C.DATASET.NUM_TEMPLATE = 0
__C.DATASET.NUM_SEARCH = 0

__C.DATASET.ALL_RESIZE = 0.6
__C.DATASET.ALL_NOT_RESIZE = 0.7
__C.DATASET.TEMPLATE.SHIFT_LOW = 4
__C.DATASET.TEMPLATE.SHIFT_HIGH = 4
__C.DATASET.TEMPLATE_RESIZE = 0.2
__C.DATASET.SEARCH.SHIFT_LOW = 64
__C.DATASET.SEARCH.SHIFT_HIGH = 128
__C.DATASET.SEARCH_RESIZE = 0.2
__C.DATASET.FETCH_ITERS = 4
__C.DATASET.NUMGENERATE_PERIMG = 12

# improve tracking performance for otb100
__C.DATASET.GRAY = 0.0

__C.DATASET.NAMES = ('VID', 'YOUTUBEBB', 'DET', 'COCO', 'GOT10K', 'LASOT','REMOCATDOGHORSE','HeadNOFACECOCO','HeadNOFACEAIC','REMOCATDOGHORSE221117','REMOWIKICATDETRESULT','REMODOGHIGDETRESULT','REMOWIKICATHIGDOGANNORESULT20230324','REMOWIKICATHIGDOGANNORESULT20230328','REMANNONOTAILDATA230525230526IMAGE','REMANNONOTAILDATA230525230526VIDEO','LASOTNOTAIL1','GOT10KNOTAIL1','VIDNOTAIL1','OBJECT365','REMANNONOTAILDATA230525230613IMAGE','REMANNONOTAILDATA0616IMAGE','AICMASK')

__C.DATASET.OBJECT365 = CN()
__C.DATASET.OBJECT365.ROOT = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/crop511'
__C.DATASET.OBJECT365.ANNO = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/train.json'
__C.DATASET.OBJECT365.FRAME_RANGE = 1
__C.DATASET.OBJECT365.NUM_USE = 1

__C.DATASET.AICMASK = CN()
__C.DATASET.AICMASK.ROOT = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/crop511'
__C.DATASET.AICMASK.ANNO = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/train.json'

__C.DATASET.REMANNONOTAILDATA230525230613IMAGE = CN()
__C.DATASET.REMANNONOTAILDATA230525230613IMAGE.ROOT = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/crop511'
__C.DATASET.REMANNONOTAILDATA230525230613IMAGE.ANNO = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/train.json'
__C.DATASET.REMANNONOTAILDATA230525230613IMAGE.FRAME_RANGE = 100
__C.DATASET.REMANNONOTAILDATA230525230613IMAGE.NUM_USE = 100000
__C.DATASET.REMANNONOTAILDATA230525230613IMAGE.NUM_USE_DOG = 100000
__C.DATASET.REMANNONOTAILDATA230525230613IMAGE.NUM_USE_CAT = 100000
__C.DATASET.REMANNONOTAILDATA230525230613IMAGE.NUM_USE_HORSE = 100000
__C.DATASET.REMANNONOTAILDATA230525230613IMAGE.NUM_USE_OTHER = 100000

__C.DATASET.REMANNONOTAILDATA0616IMAGE = CN()
__C.DATASET.REMANNONOTAILDATA0616IMAGE.ROOT = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/crop511'
__C.DATASET.REMANNONOTAILDATA0616IMAGE.ANNO = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/train.json'
__C.DATASET.REMANNONOTAILDATA0616IMAGE.FRAME_RANGE = 100
__C.DATASET.REMANNONOTAILDATA0616IMAGE.NUM_USE = 100000
__C.DATASET.REMANNONOTAILDATA0616IMAGE.NUM_USE_DOG = 100000
__C.DATASET.REMANNONOTAILDATA0616IMAGE.NUM_USE_CAT = 100000
__C.DATASET.REMANNONOTAILDATA0616IMAGE.NUM_USE_HORSE = 100000
__C.DATASET.REMANNONOTAILDATA0616IMAGE.NUM_USE_OTHER = 100000

__C.DATASET.REMANNONOTAILDATA230525230526IMAGE = CN()
__C.DATASET.REMANNONOTAILDATA230525230526IMAGE.ROOT = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/crop511'
__C.DATASET.REMANNONOTAILDATA230525230526IMAGE.ANNO = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/train.json'
__C.DATASET.REMANNONOTAILDATA230525230526IMAGE.FRAME_RANGE = 100
__C.DATASET.REMANNONOTAILDATA230525230526IMAGE.NUM_USE = 100000
__C.DATASET.REMANNONOTAILDATA230525230526IMAGE.NUM_USE_DOG = 100000
__C.DATASET.REMANNONOTAILDATA230525230526IMAGE.NUM_USE_CAT = 100000
__C.DATASET.REMANNONOTAILDATA230525230526IMAGE.NUM_USE_HORSE = 100000
__C.DATASET.REMANNONOTAILDATA230525230526IMAGE.NUM_USE_OTHER = 100000

__C.DATASET.REMANNONOTAILDATA230525230526VIDEO = CN()
__C.DATASET.REMANNONOTAILDATA230525230526VIDEO.ROOT = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/crop511'
__C.DATASET.REMANNONOTAILDATA230525230526VIDEO.ANNO = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/train.json'
__C.DATASET.REMANNONOTAILDATA230525230526VIDEO.FRAME_RANGE = 100
__C.DATASET.REMANNONOTAILDATA230525230526VIDEO.NUM_USE = 100000
__C.DATASET.REMANNONOTAILDATA230525230526VIDEO.NUM_USE_DOG = 100000
__C.DATASET.REMANNONOTAILDATA230525230526VIDEO.NUM_USE_CAT = 100000
__C.DATASET.REMANNONOTAILDATA230525230526VIDEO.NUM_USE_HORSE = 100000
__C.DATASET.REMANNONOTAILDATA230525230526VIDEO.NUM_USE_OTHER = 100000

__C.DATASET.LASOTNOTAIL1 = CN()
__C.DATASET.LASOTNOTAIL1.ROOT = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/crop511'
__C.DATASET.LASOTNOTAIL1.ANNO = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/train.json'
__C.DATASET.LASOTNOTAIL1.FRAME_RANGE = 100
__C.DATASET.LASOTNOTAIL1.NUM_USE = 100000
__C.DATASET.LASOTNOTAIL1.NUM_USE_DOG = 100000
__C.DATASET.LASOTNOTAIL1.NUM_USE_CAT = 100000
__C.DATASET.LASOTNOTAIL1.NUM_USE_HORSE = 100000
__C.DATASET.LASOTNOTAIL1.NUM_USE_OTHER = 100000

__C.DATASET.GOT10KNOTAIL1 = CN()
__C.DATASET.GOT10KNOTAIL1.ROOT = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/crop511'
__C.DATASET.GOT10KNOTAIL1.ANNO = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/train.json'
__C.DATASET.GOT10KNOTAIL1.FRAME_RANGE = 100
__C.DATASET.GOT10KNOTAIL1.NUM_USE = 100000
__C.DATASET.GOT10KNOTAIL1.NUM_USE_DOG = 100000
__C.DATASET.GOT10KNOTAIL1.NUM_USE_CAT = 100000
__C.DATASET.GOT10KNOTAIL1.NUM_USE_HORSE = 100000
__C.DATASET.GOT10KNOTAIL1.NUM_USE_OTHER = 100000

__C.DATASET.VIDNOTAIL1 = CN()
__C.DATASET.VIDNOTAIL1.ROOT = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/crop511'
__C.DATASET.VIDNOTAIL1.ANNO = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/train.json'
__C.DATASET.VIDNOTAIL1.FRAME_RANGE = 100
__C.DATASET.VIDNOTAIL1.NUM_USE = 100000
__C.DATASET.VIDNOTAIL1.NUM_USE_DOG = 100000
__C.DATASET.VIDNOTAIL1.NUM_USE_CAT = 100000
__C.DATASET.VIDNOTAIL1.NUM_USE_HORSE = 100000
__C.DATASET.VIDNOTAIL1.NUM_USE_OTHER = 100000


__C.DATASET.REMOWIKICATHIGDOGANNORESULT20230324 = CN()
__C.DATASET.REMOWIKICATHIGDOGANNORESULT20230324.ROOT = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/crop511'
__C.DATASET.REMOWIKICATHIGDOGANNORESULT20230324.ANNO = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/train.json'
__C.DATASET.REMOWIKICATHIGDOGANNORESULT20230324.FRAME_RANGE = 100
__C.DATASET.REMOWIKICATHIGDOGANNORESULT20230324.NUM_USE = 100000
__C.DATASET.REMOWIKICATHIGDOGANNORESULT20230324.NUM_USE_DOG = 100000
__C.DATASET.REMOWIKICATHIGDOGANNORESULT20230324.NUM_USE_CAT = 100000
__C.DATASET.REMOWIKICATHIGDOGANNORESULT20230324.NUM_USE_HORSE = 100000
__C.DATASET.REMOWIKICATHIGDOGANNORESULT20230324.NUM_USE_OTHER = 100000

__C.DATASET.REMOWIKICATHIGDOGANNORESULT20230328 = CN()
__C.DATASET.REMOWIKICATHIGDOGANNORESULT20230328.ROOT = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/crop511'
__C.DATASET.REMOWIKICATHIGDOGANNORESULT20230328.ANNO = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/train.json'
__C.DATASET.REMOWIKICATHIGDOGANNORESULT20230328.FRAME_RANGE = 100
__C.DATASET.REMOWIKICATHIGDOGANNORESULT20230328.NUM_USE = 100000
__C.DATASET.REMOWIKICATHIGDOGANNORESULT20230328.NUM_USE_DOG = 100000
__C.DATASET.REMOWIKICATHIGDOGANNORESULT20230328.NUM_USE_CAT = 100000
__C.DATASET.REMOWIKICATHIGDOGANNORESULT20230328.NUM_USE_HORSE = 100000
__C.DATASET.REMOWIKICATHIGDOGANNORESULT20230328.NUM_USE_OTHER = 100000

__C.DATASET.REMOWIKICATDETRESULT = CN()
__C.DATASET.REMOWIKICATDETRESULT.ROOT = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/crop511'
__C.DATASET.REMOWIKICATDETRESULT.ANNO = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/train.json'
__C.DATASET.REMOWIKICATDETRESULT.FRAME_RANGE = 100
__C.DATASET.REMOWIKICATDETRESULT.NUM_USE = 100000
__C.DATASET.REMOWIKICATDETRESULT.NUM_USE_DOG = 100000
__C.DATASET.REMOWIKICATDETRESULT.NUM_USE_CAT = 100000
__C.DATASET.REMOWIKICATDETRESULT.NUM_USE_HORSE = 100000
__C.DATASET.REMOWIKICATDETRESULT.NUM_USE_OTHER = 100000

__C.DATASET.REMODOGHIGDETRESULT = CN()
__C.DATASET.REMODOGHIGDETRESULT.ROOT = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/crop511'
__C.DATASET.REMODOGHIGDETRESULT.ANNO = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/train.json'
__C.DATASET.REMODOGHIGDETRESULT.FRAME_RANGE = 100
__C.DATASET.REMODOGHIGDETRESULT.NUM_USE = 100000
__C.DATASET.REMODOGHIGDETRESULT.NUM_USE_DOG = 100000
__C.DATASET.REMODOGHIGDETRESULT.NUM_USE_CAT = 100000
__C.DATASET.REMODOGHIGDETRESULT.NUM_USE_HORSE = 100000
__C.DATASET.REMODOGHIGDETRESULT.NUM_USE_OTHER = 100000

__C.DATASET.VID = CN()
__C.DATASET.VID.ROOT = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/crop511'
__C.DATASET.VID.ANNO = '/home/zhangming/Models2/Datasets/GOT/ILSVRC2015/train.json'
__C.DATASET.VID.FRAME_RANGE = 100
__C.DATASET.VID.NUM_USE = 100000
__C.DATASET.VID.NUM_USE_DOG = 100000
__C.DATASET.VID.NUM_USE_CAT = 100000
__C.DATASET.VID.NUM_USE_HORSE = 100000
__C.DATASET.VID.NUM_USE_OTHER = 100000

__C.DATASET.YOUTUBEBB = CN()
__C.DATASET.YOUTUBEBB.ROOT = '/home/zhangming/Models2/Datasets/GOT/youtube/youtube_new'
__C.DATASET.YOUTUBEBB.ANNO = '/home/zhangming/Models2/Datasets/GOT/youtube/train.json'
__C.DATASET.YOUTUBEBB.FRAME_RANGE = 3
__C.DATASET.YOUTUBEBB.NUM_USE = 200000
__C.DATASET.YOUTUBEBB.NUM_USE_DOG = 100000
__C.DATASET.YOUTUBEBB.NUM_USE_CAT = 100000
__C.DATASET.YOUTUBEBB.NUM_USE_HORSE = 100000
__C.DATASET.YOUTUBEBB.NUM_USE_OTHER = 100000

__C.DATASET.COCO = CN()
__C.DATASET.COCO.ROOT = '/home/zhangming/Models2/Datasets/GOT/coco/crop511'
__C.DATASET.COCO.ANNO = '/home/zhangming/Models2/Datasets/GOT/coco/train2017.json'
__C.DATASET.COCO.FRAME_RANGE = 1
__C.DATASET.COCO.NUM_USE = 100000
__C.DATASET.COCO.NUM_USE_DOG = 100000
__C.DATASET.COCO.NUM_USE_CAT = 100000
__C.DATASET.COCO.NUM_USE_HORSE = 100000
__C.DATASET.COCO.NUM_USE_OTHER = 100000

__C.DATASET.DET = CN()
__C.DATASET.DET.ROOT = '/home/zhangming/Models2/Datasets/GOT/ImageNetDet/crop511'
__C.DATASET.DET.ANNO = '/home/zhangming/Models2/Datasets/GOT/ImageNetDet/train.json'
__C.DATASET.DET.FRAME_RANGE = 1
__C.DATASET.DET.NUM_USE = 200000
__C.DATASET.DET.NUM_USE_DOG = 100000
__C.DATASET.DET.NUM_USE_CAT = 100000
__C.DATASET.DET.NUM_USE_HORSE = 100000
__C.DATASET.DET.NUM_USE_OTHER = 100000

__C.DATASET.GOT10K = CN()
__C.DATASET.GOT10K.ROOT = '/home/zhangming/Models2/Datasets/GOT/GOT10K/got10k/crop511'
__C.DATASET.GOT10K.ANNO = '/home/zhangming/Models2/Datasets/GOT/GOT10K/got10k/train.json'
__C.DATASET.GOT10K.FRAME_RANGE = 100
__C.DATASET.GOT10K.NUM_USE = 200000
__C.DATASET.GOT10K.NUM_USE_DOG = 100000
__C.DATASET.GOT10K.NUM_USE_CAT = 100000
__C.DATASET.GOT10K.NUM_USE_HORSE = 100000
__C.DATASET.GOT10K.NUM_USE_OTHER = 100000

__C.DATASET.LASOT = CN()
__C.DATASET.LASOT.ROOT = '/home/zhangming/Models2/Datasets/GOT/LaSOT/crop511'
__C.DATASET.LASOT.ANNO = '/home/zhangming/Models2/Datasets/GOT/LaSOT/train.json'
__C.DATASET.LASOT.FRAME_RANGE = 100
__C.DATASET.LASOT.NUM_USE = 200000
__C.DATASET.LASOT.NUM_USE_DOG = 100000
__C.DATASET.LASOT.NUM_USE_CAT = 100000
__C.DATASET.LASOT.NUM_USE_HORSE = 100000
__C.DATASET.LASOT.NUM_USE_OTHER = 100000

__C.DATASET.HeadNOFACECOCO = CN()
__C.DATASET.HeadNOFACECOCO.ROOT = '/home/zhangming/Models2/Datasets/GOT/LaSOT/crop511'
__C.DATASET.HeadNOFACECOCO.ANNO = '/home/zhangming/Models2/Datasets/GOT/LaSOT/train.json'

__C.DATASET.HeadNOFACEAIC = CN()
__C.DATASET.HeadNOFACEAIC.ROOT = '/home/zhangming/Models2/Datasets/GOT/LaSOT/crop511'
__C.DATASET.HeadNOFACEAIC.ANNO = '/home/zhangming/Models2/Datasets/GOT/LaSOT/train.json'


__C.DATASET.REMOCATDOGHORSE = CN()
__C.DATASET.REMOCATDOGHORSE.ROOT = '/home/zhangming/Models2/Datasets/GOT/LaSOT/crop511'
__C.DATASET.REMOCATDOGHORSE.ANNO = '/home/zhangming/Models2/Datasets/GOT/LaSOT/train.json'
__C.DATASET.REMOCATDOGHORSE.FRAME_RANGE = 100
__C.DATASET.REMOCATDOGHORSE.NUM_USE = 200000
__C.DATASET.REMOCATDOGHORSE.NUM_USE_DOG = 100000
__C.DATASET.REMOCATDOGHORSE.NUM_USE_CAT = 100000
__C.DATASET.REMOCATDOGHORSE.NUM_USE_HORSE = 100000
__C.DATASET.REMOCATDOGHORSE.NUM_USE_OTHER = 100000

__C.DATASET.REMOCATDOGHORSE221117 = CN()
__C.DATASET.REMOCATDOGHORSE221117.ROOT = '/home/zhangming/Models2/Datasets/GOT/LaSOT/crop511'
__C.DATASET.REMOCATDOGHORSE221117.ANNO = '/home/zhangming/Models2/Datasets/GOT/LaSOT/train.json'
__C.DATASET.REMOCATDOGHORSE221117.FRAME_RANGE = 100
__C.DATASET.REMOCATDOGHORSE221117.NUM_USE = 200000
__C.DATASET.REMOCATDOGHORSE221117.NUM_USE_DOG = 100000
__C.DATASET.REMOCATDOGHORSE221117.NUM_USE_CAT = 100000
__C.DATASET.REMOCATDOGHORSE221117.NUM_USE_HORSE = 100000
__C.DATASET.REMOCATDOGHORSE221117.NUM_USE_OTHER = 100000

__C.DATASET.VIDEOS_PER_EPOCH = 1000000
__C.DATASET.FLAG_CHANGEPADDING = True
__C.DATASET.CHANGEPADDING_VALUE = (117,117,117)
__C.DATASET.DATASETID = 0

__C.DATASET.FILE_CLSTAG2CLASSID_CLSTRACKER = ''


__C.DATASET.CATDOGHORSETK = CN()
__C.DATASET.CATDOGHORSETK.DATASET_ROOT = ''
__C.DATASET.CATDOGHORSETK.IMAGE_LIST = ()
__C.DATASET.CATDOGHORSETK.DATASET_ROOT_OTHERIMAGE = ""
__C.DATASET.CATDOGHORSETK.IMAGE_LIST_OTHER = ""
__C.DATASET.CATDOGHORSETK.SEGDATA_ROOT = ()
__C.DATASET.CATDOGHORSETK.SEGDATA_LIST = ()


__C.DATASET.CATDOGHORSETK.VID_LIST = ()
__C.DATASET.CATDOGHORSETK.KCONTEXTFACTOR = 0.5
__C.DATASET.CATDOGHORSETK.KCONTEXTFACTORSHIFTBOX = 2.0
__C.DATASET.CATDOGHORSETK.VIDEOS_PER_EPOCH = 600000
__C.DATASET.CATDOGHORSETK.CHANGEPADDING_VALUE = (104,117,123)
__C.DATASET.CATDOGHORSETK.GRAY = 0.0
__C.DATASET.CATDOGHORSETK.FETCH_ITERS = 1
__C.DATASET.CATDOGHORSETK.NBATCH_SHAPREPREV = 1
__C.DATASET.CATDOGHORSETK.NUM_GENERATE_PER_IMAGE = 12
__C.DATASET.CATDOGHORSETK.NUM_GENERATE_PER_FRAME = 12

__C.DATASET.CATDOGHORSETK.NUM_NEG_GENERATE_PER_IMAGE = 6
__C.DATASET.CATDOGHORSETK.NUM_NEG_GENERATE_PER_FRAME = 6
__C.DATASET.CATDOGHORSETK.NUM_NEG_OTHEROBJECT = 6
__C.DATASET.CATDOGHORSETK.PROB_NEG_OTHEROBJECT = 0.5
__C.DATASET.CATDOGHORSETK.NUM_FEATCH_SEG = 5
__C.DATASET.CATDOGHORSETK.NUM_DET = 1

__C.DATASET.CATDOGHORSETK.SEGGT_SIZE = 39

__C.DATASET.CATDOGHORSETK.TYPE_CONTEXTBOX = 0
__C.DATASET.CATDOGHORSETK.ID_PREVIMAGESHARE= -1
__C.DATASET.CATDOGHORSETK.FLAG_ENCODEGTASDET = False
__C.DATASET.CATDOGHORSETK.FLIP_TEMPLATE = 0.0
__C.DATASET.CATDOGHORSETK.FLIPVER_TEMPLATE = 0.0
__C.DATASET.CATDOGHORSETK.FLIP_SEARCH = 0.0
__C.DATASET.CATDOGHORSETK.FLIPVER_SEARCH = 0.0
__C.DATASET.CATDOGHORSETK.ROTATE_SEARCH = 0.0
__C.DATASET.CATDOGHORSETK.CROP_TEMPLATE = 0.0
__C.DATASET.CATDOGHORSETK.CROP_SCALE = 0.8

__C.DATASET.CATDOGHORSETK.NEG = 0.2
__C.DATASET.CATDOGHORSETK.PERSON_PROB = 1.0
__C.DATASET.CATDOGHORSETK.FLAG_NEGSEARCHAUG = True
__C.DATASET.CATDOGHORSETK.FLAG_TEMPLATESEARCH_SIZEFROMCONFIG = False

__C.DATASET.CATDOGHORSETK.TRIP_REPEATE_NUM = 3

__C.DATASET.CATDOGHORSETK.PROB_EREASE_BOTTOM = 0.0
__C.DATASET.CATDOGHORSETK.SCALE_EREASE_BOTTOM = 0.4
__C.DATASET.CATDOGHORSETK.PROB_NEGFROM_HEADNOFACE = 0.0
__C.DATASET.CATDOGHORSETK.PROB_PUTHEADONSEARCH = 0.0

__C.DATASET.CATDOGHORSETK.FLAG_TEMPLATEFROMIMG = False
__C.DATASET.CATDOGHORSETK.PROB_TEMPLATEFROMIMG = 0.5
__C.DATASET.CATDOGHORSETK.PROB_IMG = 0.2
__C.DATASET.CATDOGHORSETK.POSNEG_MODE = 0
__C.DATASET.CATDOGHORSETK.SHIFT_MODE = 0
__C.DATASET.CATDOGHORSETK.LAMBDA_MIN_SCALE = -0.4
__C.DATASET.CATDOGHORSETK.LAMBDA_MAX_SCALE = 0.4
__C.DATASET.CATDOGHORSETK.LAMBDA_MIN_RATIO = -0.2
__C.DATASET.CATDOGHORSETK.LAMBDA_MAX_RATIO = 0.2
__C.DATASET.CATDOGHORSETK.LAMBDA_SHIFT = 5.0
__C.DATASET.CATDOGHORSETK.LAMBDA_SCALE = 15.0

__C.DATASET.CATDOGHORSETK.COVEA = 0.5

__C.DATASET.CATDOGHORSETK.PROB_CROPTEMPLATE = 0.0
__C.DATASET.CATDOGHORSETK.SCALE_CROPTEMPLATE = 0.0
__C.DATASET.CATDOGHORSETK.DET_SAMPLERADIUS = 1.5
__C.DATASET.CATDOGHORSETK.FLAG_CLIPGT = False

__C.DATASET.CATDOGHORSETK.CROPBB = False

__C.DATASET.CATDOGHORSETK.BACKIMG_ROOT = ()
__C.DATASET.CATDOGHORSETK.BACKIMG_LIST = ()
__C.DATASET.CATDOGHORSETK.PROB_USEBACKIMG = 0.0
__C.DATASET.CATDOGHORSETK.PROB_PUTSAMEOBJECT = 0.0
__C.DATASET.CATDOGHORSETK.ERASE = 0.0
__C.DATASET.CATDOGHORSETK.ERASE_MIN = 0.0
__C.DATASET.CATDOGHORSETK.ERASE_MAX = 0.0
__C.DATASET.CATDOGHORSETK.ERASE_RATIO = 0.0

__C.DATASET.CATDOGHORSETK.PROB_RANDOMGRID = 0.0
__C.DATASET.CATDOGHORSETK.NUM_GRIDS = (1,2,3,4)
__C.DATASET.CATDOGHORSETK.RATIOMIN_GRIDS = 0.0
__C.DATASET.CATDOGHORSETK.RATIOMAX_GRIDS = 0.0


__C.DATASET.CATDOGHORSETK.RATIO_TO_SHRINK = 0.0
__C.DATASET.CATDOGHORSETK.DEFROM_MIN = 0.0
__C.DATASET.CATDOGHORSETK.DEFROM_MAX = 0.0
__C.DATASET.CATDOGHORSETK.PROB_SHRINK = 0.0
__C.DATASET.CATDOGHORSETK.RATIOMAX_TO_SHRINK = 0.0

__C.DATASET.CATDOGHORSETK.RATIO_HOR = 1.5
__C.DATASET.CATDOGHORSETK.NUMREPEAT_HOR = 5

__C.DATASET.CATDOGHORSETK.CID_SPECIFIC = -1
__C.DATASET.CATDOGHORSETK.FLAG_RANDOMCHOICEDATA = False


__C.DATASET.CATDOGHORSETK.PROB_DOG = 0.3333
__C.DATASET.CATDOGHORSETK.PROB_CAT = 0.3333
__C.DATASET.CATDOGHORSETK.PROB_HORSE = 0.3333
__C.DATASET.CATDOGHORSETK.CLASS_SAMPLELIST = [1,2,3]
__C.DATASET.CATDOGHORSETK.PROB_CROPTEMPLATE_CAT = 0.0
__C.DATASET.CATDOGHORSETK.PROB_CROPTEMPLATE_OTHER = 0.0
__C.DATASET.CATDOGHORSETK.NUM_NEG_OTHERPER = 6
__C.DATASET.CATDOGHORSETK.PERMATTING = 0.0
__C.DATASET.CATDOGHORSETK.PROB_PUTPERSONONCAT = 0.0
__C.DATASET.CATDOGHORSETK.SCALEMIN_PERSON2CAT = 0.5
__C.DATASET.CATDOGHORSETK.SCALEMAX_PERSON2CAT = 1.0

__C.DATASET.CATDOGHORSETKREID= CN()
__C.DATASET.CATDOGHORSETKREID.NUM_IDS = 16
__C.DATASET.CATDOGHORSETKREID.NUM_PERID = 4


# ------------------------------------------------------------------------ #
# Backbone options
# ------------------------------------------------------------------------ #
__C.BACKBONE = CN()

# Backbone type, current only support resnet18,34,50;alexnet;mobilenet
__C.BACKBONE.TYPE = 'mobilenetv2'

__C.BACKBONE.KWARGS = CN(new_allowed=True)
__C.BACKBONE.KWARGS.used_layers = [3,5,7]
# __C.BACKBONE.KWARGS.width_mult = 1.0
# __C.BACKBONE.KWARGS.flaglastconv = False

# Pretrained backbone weights
__C.BACKBONE.PRETRAINED = ''

__C.BACKBONE.PRETRAINED_Mode = 0
__C.BACKBONE.VARIANT = 's0'


# Train layers
__C.BACKBONE.TRAIN_LAYERS = ['layer2', 'layer3', 'layer4']

# Layer LR
__C.BACKBONE.LAYERS_LR = 0.1

# Switch to train layer
__C.BACKBONE.TRAIN_EPOCH = 5
__C.BACKBONE.TRAIN_START_LAYER = 4
__C.BACKBONE.DROPOUT=0.0
__C.BACKBONE.DROPOUTHW=0.00
# ------------------------------------------------------------------------ #
# Adjust layer options
# ------------------------------------------------------------------------ #
__C.ADJUST = CN()

# Adjust layer
__C.ADJUST.ADJUST = True

__C.ADJUST.KWARGS = CN(new_allowed=True)
#__C.ADJUST.KWARGS.in_channels = [32,96,320]
#__C.ADJUST.KWARGS.out_channels = [256,256,256]
#__C.ADJUST.KWARGS.weighted = True

# Adjust layer type
__C.ADJUST.TYPE = "MultiAdjustLayer"

# ------------------------------------------------------------------------ #
# BAN options
# ------------------------------------------------------------------------ #
__C.BAN = CN()

# Whether to use ban head
__C.BAN.BAN = True

# BAN type
__C.BAN.TYPE = 'DepthwiseBAN'

__C.BAN.KWARGS = CN(new_allowed=True)
#__C.BAN.KWARGS.in_channels = 256
#__C.BAN.KWARGS.out_channels = 256
#__C.BAN.KWARGS.cls_out_channels = 2
__C.BAN.channels = 256
# ------------------------------------------------------------------------ #
# Point options
# ------------------------------------------------------------------------ #
__C.POINT = CN()

# Point stride
__C.POINT.STRIDE = 8
__C.POINT.STRIDE_DET = 8

__C.POINT.SCALE_POS = 4.0
__C.POINT.SCALE_NEG = 2.0

__C.ANCHOR = CN()

# Point stride
__C.ANCHOR.STRIDE = 8
__C.ANCHOR.RATIOS=[0.8,1.2]
__C.ANCHOR.SCALES=[7,11,15]
__C.ANCHOR.ANCHOR_NUM=6
# ------------------------------------------------------------------------ #
# Tracker options
# ------------------------------------------------------------------------ #
__C.TRACK = CN()

__C.TRACK.TYPE = 'SiamBANTracker'

# Scale penalty
__C.TRACK.PENALTY_K = 0.14

# Window influence
__C.TRACK.WINDOW_INFLUENCE = 0.45

# Interpolation learning rate
__C.TRACK.LR = 0.30

# Exemplar size
__C.TRACK.EXEMPLAR_SIZE = 127

# Instance size
__C.TRACK.INSTANCE_SIZE = 255

# Base size
__C.TRACK.BASE_SIZE = 8

# Context amount
__C.TRACK.CONTEXT_AMOUNT = 0.5

def get_cfg_defaults():
    return __C.clone()